### ISSUE TITLE
Rest of ESL configs?

### ISSUE THREAD

**Issue by jwittorf** [Kikobeats/css-config#1]
Hi there,

thanks for your efforts, I'm just wondering if you also have a set of the other ESL settings, too. Like 1on1aml, 5on5 ladder etc.

It's been quite a while and I'm just playing with a few friends but when we play competitive I'd like to have som settings from "back in the day" ;)

Would highly appreciate it if you could help me out, couldn't find anything on the web so far.

**Comment by Kikobeats** [comment]
unfortunately I'm not an active CS:S player from time ago (but I'm playing pubg sometimes lol)

This is all that I had from the good times ¯\_(ツ)_/¯
